core/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [

    url(r'^$', views.auth, name='auth'),
    url(r'^index/$', views.index, name='index'),

    url(r'^logout/$', views.logout, name='logout'),

    url(r'^profile/$', views.profile, name='profile'),
    url(r'^help/$', views.help_view, name='help'),
    # Password Reset #
    url(r'^reset_password_confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', 
        views.reset_password_confirm, 
        name='reset_password_confirm'
    ),

    url(r'^organizations/$', views.organization_list, name='organization_list'),
    url(r'^organizations/(?P<org_pk>\d+)/$', views.organization_detail, name='organization_detail'),
    url(r'^organizations/(?P<org_pk>new)/$', views.organization_create, name='organization_create'),

    url(r'^account_create/$', views.account_create, name='account_create'),
    url(r'^organizations/(?P<org_pk>\d+)/accounts/$', views.account_list, name='account_list'),
    url(r'^organizations/(?P<org_pk>\d+)/accounts/(?P<pk>\d+)$', views.account_detail, name='account_detail'),

    url(r'^organizations/(?P<org_pk>\d+)/plants/$', views.plant_list, name='plant_list'),
    url(r'^organizations/(?P<org_pk>\d+)/plants/(?P<pk>\d+)$', views.plant_detail, name='plant_detail'),

    url(r'^plant_create/$', views.plant_create, name='plant_create'),
    url(r'^plant-upload-sample/$', views.plant_upload_sample, name='plant-upload-sample'),
    url(r'^plant-import/$', views.plant_import, name='plant-import'),
    url(r'^plant-filter/$', views.plant_filter, name='plant-filter'),

    url(r'^release_notes/$', views.release_notes, name='release_notes'),



] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

costmodel_osparc_app/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('core.urls')),
    url(r'^', include('costmodel.urls')),
    url(r'^', include('osparc.urls')),
    # url(r'^', include('osparc.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

osparc/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from osparc import views

urlpatterns = [
    url(r'^plant_time_series_create/$', views.plant_time_series_create, name='plant-time-series-create'),
    url(r'^plants/$', views.plants, name='plants'),
    url(r'^time-series-sample-download/$', views.time_series_sample_download, name='time-series-sample-download'),
    url(r'^plants/(?P<plant_pk>[0-9]+)/plant_record_data_detail$', views.plant_record_data_detail, name='time-series-list'),
    url(r'^weather-data-create/$', views.weather_data_create, name='weather-data-create'),
    url(r'^weather-data-plants/$', views.weather_data_plants, name='weather-data-plants'),
    url(r'^weather-data-plants/(?P<plant_pk>[0-9]+)/plants$', views.weather_data_list, name='weather-data-list'),
    url(r'^weather-data-sample-download/$', views.weather_data_sample_download, name='weather-data-sample-download'),
    url(r'^osparc/$', views.index, name='dashboard'),
    url(r'^osparc/create_report/$', views.create_report, name='create-report'),
    url(r'^osparc/create_report/(?P<custom_query>[0-9]+)/$', views.create_report, name='create-report'),
    url(r'^osparc/kpi_report_list/$', views.kpi_report_list, name='kpi-report-list'),
    url(r'^osparc/report_detail/(?P<pk>[0-9]+)/$', views.report_detail, name='report-detail'),
    url(r'^osparc/kpi_reports/$', views.report_detail_new, name='report-detail-new')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

osparc/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

osparc/forms.py
import requests

from django import forms

from core.constants import BASE_URL

class PlantTimeSeriesForm(forms.Form):
    time_stamp = forms.DateTimeField()
    sample_interval = forms.IntegerField()
    WH_DIFF = forms.FloatField()
    GHI_DIFF = forms.FloatField()
    TMPAMB_AVG = forms.FloatField(required=False)
    HPOA_DIFF = forms.FloatField(required=False)
    record_status = forms.IntegerField()


class WeatherDataForm(forms.Form):
    site_name = forms.CharField()
    latitude = forms.FloatField()
    longitude = forms.FloatField()
    start_time = forms.DateTimeField()
    end_time = forms.DateTimeField()

osparc/views.py
import requests
import csv
import json
import time
import MySQLdb

from bs4 import BeautifulSoup
from requests.auth import HTTPBasicAuth
import xml.etree.ElementTree as ET
import time
import os
from datetime import datetime
from dateparser import parse


from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages
from django.urls import reverse

from costmodel_osparc_app.settings import STATIC_ROOT
from core.constants import BASE_URL
from core.api import APIWrapper
from forms import (
    PlantTimeSeriesForm, WeatherDataForm
)

from core.constants import BASE_URL
from core.api import APIWrapper, APIResponseException
from core.views import login_required


@login_required
def index(request, *args, **kwargs):
    login_context = kwargs.pop('login_context')
    api = APIWrapper.from_session(login_context['sessionid'])

    stats = api.get_dashboard_stats().json()

    sc_array = stats['plants_count_by_state']
    sc_array.insert(0, ['State', 'Popularity'])

    total_plant_count = stats['total_plant_count_all']
    organization_plant_count = stats['total_plant_count_org']

    total_dc_capacity = stats['total_dc_sum_all']
    total_dc_for_org = stats['total_dc_sum_org']

    age_size_array = stats['year_dc_breakup']

    age_size_array.insert(0, [
        '', '<10kW', '<100kW', '<1MW', '<10MW', {'role': 'annotation'}
    ])

    kpis = api.kpis().json()

    if 'result' in kpis:
        kpis = json.loads(kpis['result'])
        kpis['dc_rating']['median'] = kpis['dc_rating']['median']/1000
        kpis['dc_rating']['maximum'] = kpis['dc_rating']['maximum']/1000
        kpis['dc_rating']['minimum'] = kpis['dc_rating']['minimum']/1000
        kpis['dc_rating']['mean'] = kpis['dc_rating']['mean']/1000

    login_context.update({
        'total_plant_count': total_plant_count,
        'organization_plant_count': organization_plant_count,
        'dc_capacity': int(total_dc_capacity.items()[0][-1]/1000.0),
        'total_dc_for_org': int(total_dc_for_org.items()[0][-1]/1000.0),
        'state_chart_array': json.dumps(sc_array),
        'age_size_array': json.dumps(age_size_array),
        'kpis': kpis,
    })

    return render(request, 'osparc/index.html', login_context)

@login_required
def create_report(request, *args, **kwargs):
    login_context = kwargs.pop('login_context')
    login_context['custom_query'] = {}
    api = APIWrapper.from_session(login_context['sessionid'])

    states = api.states(params={'country': 231}).json()  # 231 -> US

    cities = {}
    for state in states:
        cities[state['id']] = api.cities(params={'state': state['id']}).json()

    cq_id = kwargs.get('custom_query', False)
    if cq_id:
        try:
            custom_queries_data = api.custom_queries(id=cq_id).json()
            custom_queries_data['api_query'] = json.loads(custom_queries_data['api_query'])
            login_context['custom_query'] = json.dumps(custom_queries_data)
        except APIResponseException:
            pass

    login_context.update({
        'states': states,
        'cities': json.dumps(cities),
        'form_url': reverse('report-detail-new'),
        'button_name': 'generate_report_btn',
    })

    return render(request, 'osparc/create_report.html', login_context)

@login_required
def kpi_report_list(request, *args, **kwargs):
    login_context = kwargs.pop('login_context')

    api = APIWrapper.from_session(login_context['sessionid'])

    list_of_queries = api.custom_queries().json()
    for query in list_of_queries:
        query['date'] = parse(query['date'])

    username = api.individual_user(id=login_context['user_id']).json()

    login_context.update({'queries': list_of_queries, 'username': username})

    return render(request, 'osparc/kpi_report_list.html', login_context)

@login_required
def report_detail_new(request, *args, **kwargs):
    login_context = kwargs.pop('login_context')

    api = APIWrapper.from_session(login_context['sessionid'])


    if request.method == 'POST' and 'generate_report_btn' in request.POST:
        # Since plant can be filtered by any of its attributes
        # and the attributes are added to filter criteria dynamically
        # we iterate over all params until we have consumed all.

        count = 1
        _continue = True
        filters = {}
        p = lambda x: '{}{}'.format(
            request.POST['attribute_%d' % x],
            request.POST['comparison_attribute_%d' % x]
        )

        while _continue:
            try:
                filters[p(count)] = request.POST['value_attribute_%d' % count]
                count += 1
            except KeyError:
                _continue = False
        filters.update(
            {
                'city': request.POST.get('city', ''),
                'state': request.POST.get('state', ''),
            }
        )
        plants_resp = api.kpis_multiple_plants(
            method="post",
            data={
                'plant_filters': json.dumps(filters),
                'start_time': request.POST['observation_start_date'],
                'end_time': request.POST['observation_end_date'],
                'org_id': login_context['org_id'],
                'report_name': request.POST['name'],
                'email_desired': request.POST.get('email_desired')
            }
        )
        status = plants_resp.json()['status']

        if 'successfully' not in status:
            messages.warning(request, status)
            return redirect('create-report')
        else:
            if request.POST.get('email_desired') != 'on':
                messages.success(request, "Report Successfully Scheduled")
            else:
                messages.success(request, status)

    return redirect('kpi-report-list')


@login_required
def report_detail(request, pk, *args, **kwargs):
    login_context = kwargs.pop('login_context')
    api = APIWrapper.from_session(login_context['sessionid']) 

    # get kpi based on id value of custom query
    query_pk = pk
    # the following code breaks:
    # custom_queries = api.custom_queries(id=query_pk).json()[0]
    # I removed the [0] so that the custom query doesn't fail
    custom_queries_data = api.custom_queries(id=query_pk).json()

    def return_markup(id='', label_text='', value=''):
        return """
            <div class=" col-md-3">
                <div class="form-group">
                    <label for="{id}"
                           class="col-md- control-label"
                    >{label_text}</label>
                    <input class="form-control"
                           id="{id}"
                           type="text"
                           value="{value}"
                           disabled
                    />
                </div>
            </div>
        """.format(id=id, label_text=label_text, value=value)

    filter_map = {
        'lt': 'less than', 'lte': 'less than or equal to',
        'gt': 'greater than', 'gte': 'greater than or equal to',
        'iexact': 'equal to', 'contains': 'contains'
    }

    api_query = custom_queries_data['api_query']
    query_filters = []
    try:
        filters = json.loads(api_query)
        for k, v in filters.items():
            if 'state' in k:
                v = api.states(id=v).json()['name']
            if 'city' in k:
                v = api.cities(id=v).json()['name']
            if '__' in k:
                key, key_filter = k.split('__')
                key_filter = filter_map[key_filter]
                k = '{} ({})'.format(key, key_filter)
            query_filters.append(
                return_markup(id=k.lower().split('(')[0], label_text=k.title(), value=v)
            )
    except:
        pass

    login_context['query_filters'] = query_filters

    if custom_queries_data['kpi_result']:
        custom_queries_data.update({
            'kpi_result': json.loads(custom_queries_data['kpi_result'])
        })

    login_context.update({
        'kpi': custom_queries_data['kpi_result'],
        'report_name': custom_queries_data['report_name'],
        'cq_data': custom_queries_data,
    })

    if 'rerun_report_btn' in request.POST:
        plants_resp = api.kpis_multiple_plants(
            method="post",
            data={
                'plant_filters': custom_queries_data['api_query'],
                'start_time': custom_queries_data['start_date'],
                'end_time': custom_queries_data['end_date'],
                'org_id': login_context['org_id'],
                'report_name': custom_queries_data['report_name'],
                'email_desired': 'false',
                'cq_id': query_pk,
            }
        )
        status = plants_resp.json()['status']

        if 'successfully' in status:
            messages.success(request, "Report successfully scheduled for re-run.")

    if 'delete_report_btn' in request.POST:
        custom_queries = api.custom_queries(method='delete', id=query_pk)
        messages.success(request, "The Report was Successfully Deleted")
        return redirect('kpi-report-list')

    if 'copy_report_btn' in request.POST:
        messages.warning(
            request,
            "This form is using query parameters from an existing report "
            "to generate a new report."
        )
        return redirect('create-report', custom_query=query_pk)

    # for now, we will offer export as csv of data
    if 'query_export_btn' in request.POST:
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename="kpi_report.csv"'

        writer = csv.writer(response)
        writer.writerow(['KPI', 'Mean', 'Median', 'Minimum', 'Maximum'])

        # Update names for the kpi report csv file
        data = custom_queries_data['kpi_result']

        data['Monthly Insolation (kWh/m2)'] = data.pop('monthly_insolation')
        data['Storage Capacity (kWh)'] = data.pop('storage_capacity')

osparc/templates/osparc/create_report.html
{% extends "base.html" %}
{% block head %}Create Report {% endblock %}
{% block content %}
{% include 'plant_filters_tpl.html' %}
{% endblock %}

osparc/templates/osparc/index.html
{% extends "base.html" %}
{% block head %}oSPARC Dashboard{% endblock %}
{% block content %}

<script type="text/javascript">
  google.charts.load('current', {
    'packages':['geochart', 'corechart'],
    'mapsApiKey': 'AIzaSyD-9tSrke72PouQMnMX-a7eZSW0jkFMBWY'
  });

  google.charts.setOnLoadCallback(drawRegionsMap);
  google.charts.setOnLoadCallback(drawAgeCapacityChart);

  function drawRegionsMap() {
    var data = google.visualization.arrayToDataTable({{ state_chart_array|safe }});
    var options = {region: 'US', resolution: 'provinces', height: 400};
    var chart = new google.visualization.GeoChart(document.getElementById('state_chart'));
    chart.draw(data, options);
  }

  function drawAgeCapacityChart() {
    var data = google.visualization.arrayToDataTable({{ age_size_array|safe }});

    var options = {
      legend: { position: 'top', maxLines: 2},
      height: 400,
      bar: { groupWidth: '75%' },
      isStacked: true,
      vAxis: { title: 'Year', format: ''},
      hAxis: { title: 'Plant Count' }
    };
    var chart = new google.visualization.BarChart(document.getElementById("newplants_chart"));
    chart.draw(data, options);
  }

window.addEventListener('resize', drawRegionsMap);
window.addEventListener('resize', drawAgeCapacityChart);

</script>

<div class="container-fluid">

  <!-- quick stats start here -->
  <div class="panel panel-info">
    <div class="panel-heading">Quick Stats</div>
    <div class="panel-body">
      <div class="row">
        <div class="col-md-3">
          <h5 style="margin-left: 10px;">Total Number of plants
            <h4 style="margin-left: 10px;"class="text-left">{{ total_plant_count }}</h3>
          </h5>
        </div>

        <div class="col-md-3">
          <h5 style="margin-left: 10px;">Number of plants in Organization
            <h4 style="margin-left: 10px;"class="text-left">{{ organization_plant_count }}</h3>
          </h5>
        </div>

        <div class="col-md-3">
          <h5 style="margin-left: 10px;">Total rated DC Capacity
            <h4 style="margin-left: 10px;" class="text-left">{{ dc_capacity }} kW</h3>
          </h5>
        </div>

        <div class="col-md-3">
          <h5 style="margin-left: 10px;">Total rated DC Capacity for Organization
            <h4 style="margin-left: 10px;" class="text-left">{{ total_dc_for_org }} kW</h3>
          </h5>
        </div>
      </div>
    </div>
  </div>
  <!-- quick stats end here -->

  <!-- Charts start here -->

      <div class="panel panel-info">
        <div class="panel-heading">Plants by State</div>
        <div class="panel-body">
          <div class="row">
            <div class="col-sm-12">
              <div id="state_chart" align="center"></div>
            </div>
          </div>
        </div>
      </div>

      <div class="panel panel-info">
        <div class="panel-heading">Plants by Age and Capacity</div>
        <div class="panel-body">
          <div class="row">
            <div class="col-sm-12">
              <div id="newplants_chart" align="center"></div>
            </div>
          </div>
        </div>
      </div>
    <!-- charts end here -->

    {% if not kpis.status %}
    <!-- metrics start here -->
    <div class="row">
      <div class="col-md-12">
        <div class="panel panel-info">
          <div class="panel-heading">Energy Performance Metrics</div>
          <div class="panel-body">
            <table class="table table-striped">
              <thead class="thead-inverse">
                <tr>
                  <th>KPI</th>
                  <th>Mean</th>
                  <th>Median</th>
                  <th>Minimum</th>
                  <th>Maximum</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th scope="row">Monthly Insolation (<small>kWh/m<sup>2</sup></small>)</th>
                  <td>{{ kpis.monthly_insolation.mean }}</td>
                  <td>{{ kpis.monthly_insolation.median }}</td>
                  <td>{{ kpis.monthly_insolation.minimum }}</td>
                  <td>{{ kpis.monthly_insolation.maximum }}</td>
                </tr>
                <tr>
                  <th scope="row">DC Power Rating (<small>kW</small>)</th>
                  <td>{{ kpis.dc_rating.mean }}</td>
                  <td>{{ kpis.dc_rating.median }}</td>
                  <td>{{ kpis.dc_rating.minimum }}</td>
                  <td>{{ kpis.dc_rating.maximum }}</td>
                </tr>
                <tr>
                  <th scope="row">Monthly AC Energy (<small>MWh</small>)</th>
                  <td>{{ kpis.monthly_yield.mean }}</td>
                  <td>{{ kpis.monthly_yield.median }}</td>
                  <td>{{ kpis.monthly_yield.minimum }}</td>
                  <td>{{ kpis.monthly_yield.maximum }}</td>
                </tr>
                <tr>
                  <th scope="row">Monthly DC Energy (<small>kWh</small>)</th>
                  <td>{{ kpis.monthly_generated_energy.mean }}</td>
                  <td>{{ kpis.monthly_generated_energy.median }}</td>
                  <td>{{ kpis.monthly_generated_energy.minimum }}</td>
                  <td>{{ kpis.monthly_generated_energy.maximum }}</td>
                </tr>
                <tr>
                  <th scope="row">Performance Ratio</th>
                  <td>{{ kpis.performance_ratio.mean }}</td>
                  <td>{{ kpis.performance_ratio.median }}</td>
                  <td>{{ kpis.performance_ratio.minimum }}</td>
                  <td>{{ kpis.performance_ratio.maximum }}</td>
                </tr>
                <tr>
                  <th scope="row">Storage Capacity (<small>kWh</small>)</th>
                  <td>{{ kpis.storage_capacity.mean }}</td>
                  <td>{{ kpis.storage_capacity.median }}</td>
                  <td>{{ kpis.storage_capacity.minimum }}</td>
                  <td>{{ kpis.storage_capacity.maximum }}</td>
                </tr>
                <tr>
                  <th scope="row">Storage State of Health</th>
                  <td>{{ kpis.storage_state_of_health.mean }}</td>
                  <td>{{ kpis.storage_state_of_health.median }}</td>
                  <td>{{ kpis.storage_state_of_health.minimum }}</td>
                  <td>{{ kpis.storage_state_of_health.maximum }}</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>

    </div>
    <!-- metrics end here -->

    {% else %}

    <div class="row">
      <div class="col-md-12">
        <div class="panel panel-info">
          <div class="panel-heading">Energy Performance Metrics</div>
          <div class="panel-body" style="height: 245px;">
            Please be patient as we calculate your KPI report here. Refresh your page momentarily to see if the calculation is done.
          </div>
        </div>
      </div>
    {% endif %}  
    

</div>

{% endblock %}

osparc/templates/osparc/weather_data_create.html
{% extends "core/base.html" %}

{% block head %}Create Plant Weather Data{% endblock %}

{% block content %}

    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}"><strong>{{ message }}</strong></div>
    {% endfor %}


<div class="panel panel-info">        
    <div class="panel-heading"><strong>Select A Plant to Assign Weather Data To</strong></div>
        <div class="panel-body">
            <div class="row">
                <div class="col-lg-12">
                    <div class="table-responsive">
                        <table id ="list_table" class="table table-striped table-bordered table-hover">
                            <thead>
                                <tr>
                                    <td><strong>Available Plants</strong></td>
                                </tr>
                            </thead>
                            <tbody>
                                {% for plant in plant_list %}
                                    <tr id={{ plant.id }}>
                                        <td>{{ plant.name }}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <form class="form-horizontal" role="form" id="form" method="post" action=".">{% csrf_token %}
        <div class="row" style="padding-top: 20px">
            <div class="col-lg-12">
                <div class="panel panel-info">
                    <div class="panel-heading"><strong>Get Weather Data from Solar Anywhere</strong></div>
                    <div class="panel-body">

                        <div class="row">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="control-label col-xs-4">Start Time</label>
                                    <div class="col-xs-6">
                                        <input type="datetime-local" name="start_time" step="any" id="id_start_time" class="form-control input-sm" required/>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="control-label col-xs-4">End Time</label>
                                    <div class="col-xs-6">
                                        <input type="datetime-local" name="end_time" step="any"  id="id_end_time" class="form-control input-sm" required/>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12">
                                <button type="submit" class="btn btn-primary" data-tooltip="tooltip" title="Please Select A Plant To Enable Button" id="weather_data_btn" name="weather_data_btn">Get Weather Data from Solar Anywhere</button>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
 
    </form>

    <!-- Import weather data from CSV -->
    <!--<div class="row" style="padding-top: 20px">
        <div class="col-lg-12">
            <div class="panel panel-info">
                <div class="panel-heading"><strong>Import Weather Data from CSV</strong></div>
                <div class="panel-body">

                    <div class="row">
                        <div class="col-lg-12">
                            <ul class="list-group">
                                <li class="list-group-item">To Upload Weather Data, please select and upload a CSV file. To see a sample of the CSV format, click <a href="/static/core/example_files/WeatherDataExample.csv"><u>here</u></a> to download.</li>
                            </ul>
                        </div>

                        <div class="row">
                            <div class="col-lg-12">
                                <button type="button" name="importModal" class="btn btn-primary" data-toggle="modal" data-tooltip="tooltip" title="Please Select A Plant To Enable Button" id="csv_button" data-target="#importModal" style="margin: 0px 0px 0px 15px;">Upload from CSV</button>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>-->

</div>

    <!-- Import Modal -->
    <div class="modal fade" id="importModal" tabindex="-1" role="dialog" aria-labelledby="importModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Upload Weather Data</h4>
            </div>
            <form class="form-horizontal" role="form" method="post" action="." enctype="multipart/form-data">{% csrf_token %}
                <div class="modal-body">
                    <p>Choose a CSV file to create Weather Data for your Plant<br>
                        Use a format that matches the Template <br> <br>
                    <input id="plant_id" type="hidden" value=""/>
                    <input type="file" accept=".csv" name="datafile" required></p>
                    <p>View Template <a href="/static/core/example_files/WeatherDataExample.csv"><u>HERE</u></a></p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary" name="import_weather_data_btn">Upload from CSV</button>
                </div>
            </form>
            </div>
        </div>
    </div>

    <style>
        .list-group-item { border-color: #337ab7; }
    </style>

    <!-- Scripts -->
    <script type="text/javascript">
        $(document).ready(function() {
            var table = $('#list_table').DataTable({
                dom: "Bfrtip",
                responsive: true,
                serverSide: true,
                processing: true,
                pageLength: 10,
                select: true,
                ajax: {
                    url: "/organizations/{{ org_id }}/plants/",
                    type: "POST",
                    data: {
                        csrfmiddlewaretoken: "{{ csrf_token }}"
                    },
                    dataType: "json",
                },
                columns: [
                    { data: "name" },
                ],
                "searching": false,
                "ordering": false,
            });

            $('#list_table tbody').on( 'click', 'tr', function () {
                if ( $(this).hasClass('selected') ) {
                    $(this).removeClass('selected');
                    $("#csv_button").attr("disabled", "disabled");
                    $('#plant_id').val('');
                }
                else {
                    table.$('tr.selected').removeClass('selected');

                    $(this).addClass('selected');
                    $("#csv_button").removeAttr("disabled data-tooltip title");
                    $("#weather_data_btn").removeAttr("disabled data-tooltip title");
                    plantid = table.row( this ).data().id
                    $('form.form-horizontal').attr('action', document.URL + '?' + 'plant_id='+plantid)
                }
            });
        });

        document.onload = $("#csv_button").attr("disabled", "disabled");
        document.onload = $("#weather_data_btn").attr("disabled", "disabled");
        $('[data-tooltip="tooltip"]').tooltip();

    </script>

{% endblock %}